# Generated by Django 4.2.16 on 2025-10-07 00:59

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='confiabilidad',
            field=models.IntegerField(default=100, help_text='Confiabilidad del proveedor (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dias_pago',
            field=models.IntegerField(default=30, help_text='Días de plazo de pago', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Marca si es dato de demostración'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
