# Generated by Django 4.2.16 on 2025-10-14 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_ordencompra_ordencompraitem_movimientostock_and_more'),
        ('proveedores', '0002_proveedor_confiabilidad_proveedor_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('urgent', 'Urgente'), ('overdue', 'Vencido'), ('paid', 'Pagado')], default='pending', max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('is_demo', models.BooleanField(default=False, help_text='Marca si es dato de demostración')),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.ordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_por_pagar', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Cuenta por Pagar',
                'verbose_name_plural': 'Cuentas por Pagar',
                'ordering': ['fecha_vencimiento', '-fecha_creacion'],
            },
        ),
    ]
