# Generated by Django 4.2.16 on 2025-10-14 17:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_identificacion_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del rubro')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='rubro',
            field=models.ForeignKey(blank=True, help_text='Tipo de negocio del cliente (ej: Supermercado, Kiosco, Fábrica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.rubro'),
        ),
    ]
