# Generated by Django 4.2.16 on 2025-10-07 00:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_categoria_marca_producto_categoria_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='avg_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Costo promedio móvil', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='producto',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Marca si es dato de demostración'),
        ),
        migrations.AddField(
            model_name='producto',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Stock mínimo para alertas', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('u', 'Unidades'), ('l', 'Litros'), ('m', 'Metros'), ('m2', 'Metros cuadrados'), ('m3', 'Metros cúbicos'), ('caja', 'Cajas'), ('paquete', 'Paquetes')], default='u', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Stock actual (currentStock)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
