# Generated by Django 5.0.14 on 2025-09-24 23:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('finanzas_reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocliente',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('referencia_extra', models.CharField(blank=True, max_length=100)),
                ('compra', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_financiero', to='compras.compra')),
            ],
            options={
                'verbose_name': 'movimiento financiero',
                'verbose_name_plural': 'movimientos financieros',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
