# Generated by Django 5.0.14 on 2025-09-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_reportes', '0002_alter_pagocliente_fecha_movimientofinanciero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocliente',
            name='medio',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque')], default='EFECTIVO', max_length=20),
        ),
    ]
