# Generated by Django 5.0.14 on 2025-09-25 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas_reportes', '0003_alter_pagocliente_medio'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='origen',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('PAGO_EMPLEADO', 'Pago empleado')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_financiero', to='ventas.venta'),
        ),
    ]
