# Generated by Django 4.2.16 on 2025-10-05 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('permisos', models.JSONField(default=dict, help_text='Permisos específicos del rol')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='pagoempleado',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Pago de Empleado', 'verbose_name_plural': 'Pagos de Empleados'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='empleado',
            name='especialidad',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='empleado',
            name='experiencia_anos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='salario_por_hora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='turno',
            field=models.CharField(choices=[('manana', 'Turno Mañana (6:00-14:00)'), ('tarde', 'Turno Tarde (14:00-22:00)'), ('noche', 'Turno Noche (22:00-6:00)'), ('completo', 'Tiempo Completo'), ('parcial', 'Tiempo Parcial')], default='completo', max_length=20),
        ),
        migrations.AddField(
            model_name='pagoempleado',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagoempleado',
            name='horas_trabajadas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='identificacion',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('produccion', 'Producción'), ('logistica', 'Logística'), ('administracion', 'Administración'), ('ventas', 'Ventas'), ('calidad', 'Control de Calidad'), ('mantenimiento', 'Mantenimiento')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('modificar', 'Modificar'), ('eliminar', 'Eliminar'), ('activar', 'Activar'), ('desactivar', 'Desactivar')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='recursos_humanos.equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Equipo',
                'verbose_name_plural': 'Auditorías de Equipos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('modificar', 'Modificar'), ('eliminar', 'Eliminar'), ('activar', 'Activar'), ('desactivar', 'Desactivar'), ('cambiar_equipo', 'Cambiar Equipo'), ('cambiar_rol', 'Cambiar Rol')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='recursos_humanos.empleado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Empleado',
                'verbose_name_plural': 'Auditorías de Empleados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='miembros', to='recursos_humanos.equipo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='recursos_humanos.rol'),
        ),
    ]
