# Generated by Django 4.2.16 on 2025-10-05 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0002_rol_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='lider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_liderados', to='recursos_humanos.empleado'),
        ),
    ]
